[package]
name = "fs0-volume"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
fs0-core.workspace = true
libc.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
tracing.workspace = true
windows-sys.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
