[package]
name = "fs0-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fs0-core.workspace = true
iroh.workspace = true
iroh-relay.workspace = true
postcard.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["io-util"] }
