[package]
name = "fs0-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Configuration types and loading utilities for fs0."
readme = "../../README.md"

[dependencies]
fs0-core.workspace = true
serde.workspace = true
toml.workspace = true
