[package]
name = "fs0-central"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
fs0-config.workspace = true
fs0-core.workspace = true
fs0-transport.workspace = true
iroh.workspace = true
iroh-relay = { workspace = true, features = ["server"] }
parking_lot.workspace = true
rcgen.workspace = true
rusqlite.workspace = true
rustls.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
