[package]
name = "fs0-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rust client library for fs0 distributed storage."
readme = "../../README.md"

[dependencies]
blake3.workspace = true
fs0-config.workspace = true
fs0-core.workspace = true
fs0-transport.workspace = true
iroh.workspace = true
parking_lot.workspace = true
postcard.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "net", "rt", "sync"] }
tracing.workspace = true
